apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sim-deployment
  labels:
    app: sim
spec:
  selector:
    matchLabels:
      app: sim
  replicas: 1
  template:
    metadata:
      labels:
        app: sim
    spec:
      containers:
        - name: sim
          image: olamai/simulation:0.0.1
          imagePullPolicy: Never
          ports:
            - name: sim-service
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sim-service
spec:
  type: NodePort
  selector:
    app: sim
  ports:
    - port: 8080
      targetPort: sim-service
