apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simulation
spec:
  selector:
    matchLabels:
      app: simulation
  replicas: 1
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
        - name: simulation
          image: olamai/simulation:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: simulation
  labels:
    app: simulation
spec:
  type: NodePort
  selector:
    app: simulation
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
